---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
# Adding Resource limits for DEV Environment
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-limits-dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: qa
---
apiVersion: v1
kind: Namespace
metadata:
  name: int

---
apiVersion: v1
kind: Namespace
metadata:
  name: load